INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Irvine', '3', 'fire', 'backup', 'Sniper', 'VIII', 'When Irvine enters the field, choose 1 forward. Deal it 6000 damage.', '1', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ifrit', '2', 'fire', 'summon', '', 'VIII', 'Choose 1 Forward. Deal it 6000 damage.', '2', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ward', '3', 'fire', 'forward', 'Warrior', 'VIII', 'When Ward attacks, Ward gains +3000 power until the end of the turn.', '3', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ephemeral Phantom', '2', 'fire', 'forward', 'Manikin', 'DFF', 'When your opponent controls 2 or more Forwards, Ephemeral Phantom gains +2000 power.', '4', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Sage', '2', 'fire', 'backup', 'Standard Unit', 'III', 'When Sage enters the field, choose 1 Forward. It gains <b>Haste</b> until end of the turn.', '5', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Sazh', '2', 'fire', 'forward', 'Ravager', 'XIII', 'When Sazh attacks, choose 1 Forward opponent controls. Deal it 1000 damage for each point of damage you have received.', '6', 'R', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Emperor Xande', '5', 'fire', 'forward', 'Emperor', 'XIV', 'You can only pay with Fire CP to play Emperor Xande onto the field. </p><p>When Emperor Xande attacks, choose 1 Forward opponent controls. Deal it 5000 damage. </p><p></p><p>When Emperor Xande is put from the field into the Break Zone, choose 1 Forward opponent controls. Deal it 9000 damage.', '7', 'L', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Zell', '3', 'fire', 'forward', 'SeeD Candidate', 'VIII', 'When Zell attacks, choose 1 Forward of cost 3 or less opponent controls. It cannot block this turn.', '8', 'C', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Selphie', '2', 'fire', 'backup', 'SeeD Candidate', 'VIII', '<img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 attacking Forward. It gains +2000 power until the end of the turn', '9', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Warrior', '2', 'fire', 'forward', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/fire.png" />: Warrior gains +1000 power until the end of the turn.', '10', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Tifa', '5', 'fire', 'forward', 'Martial Artist', 'DFF - VII', 'When Tifa attacks, choose 1 Forward. It cannot block this turn.</p><p></p><p>Falcon\'s Dive <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/fire.png" />: All Forwards of cost 3 or less cannot block this turn.', '11', 'L', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Tellah', '4', 'fire', 'backup', 'Sage', 'IV', '<img class="small-icon" src="/img/icons/dull.png" />, put Tellah into the Break Zone: Choose 1 Forward. Deal it 9000 damage.', '12', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ninja', '2', 'fire', 'forward', 'Standard Unit', 'III', '<b>First Strike</b></p><p></p><p>When Ninja is blocked, deal the blocking forward 2000 damage.', '13', 'C', '4000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Basch', '3', 'fire', 'forward', 'Captain', 'XII', 'If you control [Card name (Ashe)], Basch gains +2000 power.</p><p></p><p>Flame Purge <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/fire.png" /><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">2</span></span><img class="small-icon" src="/img/icons/dull.png" />: Choose up to 2 Forwards. Deal them 9000 damage.', '14', 'H', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Palom', '3', 'fire', 'forward', 'Black Mage', 'IV', 'When Palom enters your field other than from your hand, choose 1 Forward. You may deal it 7000 damage.</p><p></p><p>Comet <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/dull.png" />, Dull 1 active [Card Name (Porom)]: Deal your opponent 1 point of damage.', '15', 'H', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Palom', '1', 'fire', 'forward', 'Apprentice Mage', 'IV', 'When Palom attacks, choose 1 Forward opponent controls. Deal it 2000 damage.</p><p></p><p>When Palom deals damage to your opponent, or when the Forward damaged by Palom is put from the field into the Break Zone during the same turn, you may put Palom into the Break Zone. If you do so, search for 1 [Card Name (Palom)], and play it onto the field.', '16', 'R', '1000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Bergan', '4', 'fire', 'forward', 'Judge', 'XII', '<img class="small-icon" src="/img/icons/fire.png" /><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">1</span></span>: Deal all the Forwards opponent controls 1000 damage. </p><p></p><p>When Bergan is chosen by a Summon, put Bergan into the Break Zone.', '17', 'R', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Summoner', '2', 'fire', 'backup', 'Standard Unit', 'III', '<img class="small-icon" src="/img/icons/dull.png" />, put Summoner into the Break Zone: If a Forward receives damage this turn, that damage increases by 1000 instead.', '18', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Belias, the Gigas', '2', 'fire', 'summon', '', 'XII', 'EX BURST Choose 1 Forward. Until the end of the turn, it gains +1000 power, <b>Haste</b> and <b>First Strike</b>. Draw 1 Card.', '19', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Imitation Liegeman', '3', 'fire', 'forward', 'Manikin', 'DFF', 'When Imitation Liegeman enters the field, choose 1 Forward opponent controls. Deal it 2000 damage. If you control a [Job (Manikin)] other than Imitation Liegeman, deal it 5000 instead.', '20', 'C', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Montblanc', '2', 'fire', 'backup', 'Moogle', 'XII', '<img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/fire.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Deal it 1000 damage for each [Job (Moogle)] you control.', '21', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Luneth', '3', 'fire', 'forward', 'Warrior of Light', 'III', 'The [Job (Standard Unit)] Forwards you control gain <b>Haste</b>', '22', 'H', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rubicante', '4', 'fire', 'forward', 'Archfiend', 'IV', 'When Rubicante attacks, activate all the Forwards opponent controls. </p><p></p><p>Barrier Shift <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/fire.png" />: Name 1 Element. Rubicante cannot be chosen by Summons or abilities of the named Element this turn.', '23', 'H', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rosso', '3', 'fire', 'forward', 'Tsviets', 'VII', 'If Rosso receives damage, reduce the damage by half instead (numbers are rounded up to units of 1000)', '24', 'R', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Weiss', '6', 'ice', 'forward', 'Tsviets', 'VII', 'When Weiss enters the field, you may play 1 Ice Forward of cost 3 or less from your hand onto the field.</p><p></p><p>When Weiss attacks, Weiss gains +2000 power until the end of the turn.', '25', 'H', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Vayne', '4', 'ice', 'forward', 'Consul', 'XII', 'The Forwards of cost 5 or more opponent controls won\'t activate at the controller\'s Active Phase.</p><p></p><p>When Vayne enters the field, dull all the Forwards of cost 5 or more opponent controls.</p><p></p><p>Force of Will <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/ice.png" />: <b>Freeze</b> all the Forwards opponent controls.', '26', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Scholar', '2', 'ice', 'backup', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/dull.png" /> : Choose 1 dull Forward. Deal it 2000 damage.', '27', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Semblance of a Lion', '2', 'ice', 'forward', 'Manikin', 'DFF', 'When Semblance of a Lion blocks or is blocked, choose 1 Forward. Deal it 2000 damage.', '28', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Imaginary Champion', '3', 'ice', 'forward', 'Manikin', 'DFF', 'When Imaginary Champion enters the field, each player discards 1 card from his/her hand.', '29', 'C', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Edward', '4', 'ice', 'backup', 'Bard', 'IV', '<img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Dull it.', '30', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Edward', '2', 'ice', 'forward', 'Bard', 'IV', 'All forwards lose <b>Haste</b></p><p></p><p>Forwards cannot gain <b>Haste</b>', '31', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Bard', '2', 'ice', 'backup', 'Standard Unit', 'XIV', 'When Bard enters the field, Dull all the Backups opponent controls.', '32', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Black Mage', '3', 'ice', 'backup', 'Standard Unit', 'III', 'Put Black Mage into the Break Zone: No Forward of cost 3 or less can attack this turn.', '33', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Zargabaath', '3', 'ice', 'forward', 'Judge', 'XII', 'TextWhen Zargabaath enters the field, you may play a Forward of any Element except Ice and of cost 3 or less from your hand on to the field.', '34', 'R', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Shelke', '3', 'ice', 'forward', 'Tsviets', 'VII', 'When Shelke enters the field, you may play a Forward of any Element except Ice and of cost 2 or less from your hand onto the field. If you do so, your opponent discards 1 card from his/her hand.', '35', 'H', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Shalua', '2', 'ice', 'backup', 'Scientist', 'VII', 'The [Card name (Shelke)] you control gains +2000 power.</p><p></p><p><img class="small-icon" src="/img/icons/dull.png" />, put Shalua into the Break Zone: The next damage dealt to [Card Name (Shelke)] becomes 0 this turn.', '36', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Jihl Nabaat', '2', 'ice', 'backup', 'PSICOM', 'XIII', 'Backups don\'t deal damage to the Forwards you control.', '37', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Squall', '5', 'ice', 'forward', 'SeeD Candidate', 'DFF - VIII', '<b>First Strike</b></p><p></p><p>For each dull Character opponent controls, Squall gains +1000 power.</p><p></p><p>When Squall attacks, dull all the Backups opponent controls.', '38', 'H', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Capricious Reaper', '4', 'ice', 'forward', 'Manikin', 'DFF', 'When Capricious Reaper is chosen by your opponent\'s Summons or abilities, your opponent discards 1 card from his/her hand.', '39', 'C', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Time Mage', '2', 'ice', 'backup', 'Standard Unit', 'FFT', '<img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. It loses <b>Haste</b> and <b>First Strike</b> until the end of the next turn.', '40', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Doctor Cid', '2', 'ice', 'backup', 'Research Chief', 'XII', 'When a Backup you control is broken by your opponent\'s Summon or ability, your opponent puts 1 Character from his field into the Break Zone.', '41', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Nero', '3', 'ice', 'forward', 'Tsviets', 'VII', 'If you control [Card Name (Weiss)], Nero gains +1000 power.</p><p>When Nero blocks or is blocked, choose 1 Forward. <b>Freeze</b> it.', '42', 'R', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Hurdy', '2', 'ice', 'backup', 'Moogle', 'XII', '<img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/dull.png" />: Dull all the Forwards with a cost equal to the number of [Job (Moogle)] you control.', '43', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Mateus, the Corrupt', '5', 'ice', 'summon', '', 'XII', 'EX BURST Opponent puts 1 attacking Forward into the Break Zone', '44', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Moomba', '2', 'ice', 'summon', '', 'VIII', 'EX BURST Choose 1 Forward. Deal it damage equal to its power minus 1000', '45', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Laguna', '3', 'ice', 'forward', 'Marksman', 'VIII', '<b>First Strike</b></p><p></p><p>When Laguna attacks, choose 1 dull Forward opponent controls. <b>Freeze</b> it.', '46', 'R', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rinoa', '3', 'ice', 'forward', 'Resistance Fighter', 'VIII', 'or each [Category (VIII)] Forward other than Rinoa you control, Rinoa gains +1000 Power.</p><p></p><p>When Rinoa is put from the field into the Break Zone, dull all Forwards opponent controls.</p><p></p><p>Wishing Star <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/ice.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward and 1 Backup. Dull them and <b>Freeze</b> them.', '47', 'L', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rinoa', '3', 'ice', 'backup', 'Resistance Fighter', 'VIII', 'When Riona enters the field, you may search for 1 [Category (VIII)] Forward and add it to your hand.', '48', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Asura', '1', 'wind', 'summon', '', 'IV', 'Select 1 of the 3 following actions.</p><p>"Choose up to 2 Forwards. Activate them."</p><p>"Choose up to 5 Backups. Activate them."</p><p>"Choose 1 Character card of cost 2 or less in your Break Zone. Add it to your hand."', '49', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Arc', '2', 'wind', 'backup', 'Warrior of Light', 'III', 'The [Job (Standard Unit)] Forwards you control gain +1000 Power.', '50', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Vaan', '4', 'wind', 'forward', 'Sky Pirate', 'XII', 'When Vaan attacks, choose 1 Forward you control. You may return 1 Backup of cost 2 or less you control to its owner\'s hand. If you do so, activate the Forward.</p><p></p><p>White Whorl <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/wind.png" /> : Activate all the Wind Characters you control.', '51', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Vaan', '1', 'wind', 'forward', 'Sky Pirate', 'XII', 'When Vaan enters the field or attacks, choose 1 Backup you control. Activate it.', '52', 'C', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Edge', '4', 'wind', 'forward', 'Ninja', 'IV', 'The [Job (Ninja)] and [Card Name (Ninja)] Forwards other than Edge you control gain +1000 power and <b>First Strike</b>', '53', 'H', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Edge', '2', 'wind', 'forward', 'Ninja', 'IV', 'Edge cannot be blocked by a Forward of cost 4 or more.</p><p>When Edge deals damage to your opponent, activate all the backups you controlWhen Edge deals damage to your opponent, activate all the backups you control', '54', 'R', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Kan-E-Senna', '5', 'wind', 'backup', 'Praetor', 'XIV', 'When Kan-E-Senna enters the field, choose 1 forward of cost 5 or more opponent controls. Break it.', '55', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ranger', '2', 'wind', 'backup', 'Standard Unit', 'III', '<img class="small-icon" src="/img/icons/dull.png" />, put Ranger into the Break Zone: Choose 1 backup of cost 1. Break it.', '56', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Cid Pollendina', '3', 'wind', 'forward', 'Engineer', 'IV', '<img class="small-icon" src="/img/icons/dull.png" />: Your opponent shows his/her hand.', '57', 'C', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'White Mage', '3', 'wind', 'backup', 'Standard Unit', 'XIV', 'When White Mage enters the field, choose up to 2 wind character. Activate them.', '58', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Capricious Thief', '2', 'wind', 'forward', 'Manikin', 'DFF', 'Capricious Thief cannot be blocked by a Forward of cost 5 or more.</p><p>Capricious Thief cannot be chosen by your opponents Summons or Abilities during your opponent\'s turn.', '59', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Chocobo', '1', 'wind', 'forward', 'Standard Unit', 'VIII', '<b>First Strike</b></p><p></p><p>The Forwards forming a party with Chocobo gain <b>First Strike</b>', '60', 'C', '1000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ninja', '1', 'wind', 'forward', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" />: If Ninja deals damage to a Forward this turn, double the damage instead.', '61', 'C', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Nono', '2', 'wind', 'backup', 'Moogle', 'XII', '<img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose as many Forwards as [Job (Moogle)] you control. Activate them.', '62', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Paine', '3', 'wind', 'forward', 'Gullwings', 'X', 'EX BURST When Paine enters the field, you may search for 1 [Card Name (Yuna)] or 1 [Card Name (Rikku)] and add it to your hand.', '63', 'R', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Barbariccia', '3', 'wind', 'forward', 'Archfiend', 'IV', 'Maelstrom <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/dull.png" />: Deal each Forward opponent controls damage equal to its power minus 1000.', '64', 'H', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Balthier', '4', 'wind', 'forward', 'Sky Pirate', 'XII', 'Whenever one of your Backups enters the field, activate Balthier.</p><p></p><p><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Deal it 2000 damage.</p><p></p><p>Fires of War <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/wind.png" /> : Balthier cannot be chosen by a Summon or an ability this turn and gains <b>First Strike</b> until the end of the turn', '65', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Balthier', '3', 'wind', 'forward', 'Sky Pirate', 'XII', 'When Balthier enters the field, you may search for 1 [Card Name (Fran)] and add it to your hand.', '66', 'R', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Penelo', '2', 'wind', 'backup', 'Dancer', 'XII', 'If all the Forwards you control have [Job (Sky Pirate)] or [Job (Pirate)], they gain +1000 power.', '67', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Fran', '2', 'wind', 'backup', 'Sky Pirate', 'XII', '<img class="small-icon" src="/img/icons/dull.png" />: Choose 1 [Card Name (Balthier)]. It gains +1000 power until the end of the turn.</p><p></p><p><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 [Card Name (Balthier)]. It gains <b>Haste</b> until the end of the turn.', '68', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Fallacious Wanderer', '3', 'wind', 'forward', 'Manikin', 'DFF', 'When Fallacious Wanderer enters the field, choose up to 2 Wind Characters you control. Activate them.', '69', 'C', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Shemhazai, the Whisperer', '1', 'wind', 'summon', '', 'XII', 'Each Forward can only be blocked by a Forward with a cost inferior or equal to its own this turn.', '70', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rikku', '2', 'wind', 'backup', 'Gullwings', 'X', 'EX BURST When Rikku enters the field, activate all the Forwards you control.', '71', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Reddas', '5', 'wind', 'forward', 'Sky Pirate', 'XII', 'tReddas must attack once per turn if possible.</p><p></p><p>When Reddas attacks, the Forwards other than Reddas you control gain +1000 power until the end of the turn.', '72', 'C', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Dark Knight', '4', 'earth', 'forward', 'Standard Unit', 'XIV', 'For each point of damage you have received, Dark Knight gains +1000 power.', '73', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Warrior of Antiquity', '3', 'earth', 'forward', 'Manikin', 'DFF', 'For each point of damage you have received Warrior of Light Antiquity gains +1000 power.</p><p></p><p>For each point of damage you have received Warrior of Light Antiquity gains +1000 power.</p><p></p><p>If you have received 6 points of damage, put Warrior of Antiquity into the Break Zone.', '74', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ingus', '4', 'earth', 'forward', 'Warrior of Light', 'III', 'When Ingus enters the field, you may play 1 [Job (Standard Unit)] of cost 2 or less from your hand onto the field.', '75', 'H', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Vanille', '6', 'earth', 'forward', 'Medic', 'XIII', 'When Vanille enters the field, you may play 1 Earth Forward of cost 4 or less from your hand onto the field.', '76', 'R', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Vincent', '4', 'earth', 'forward', 'Gunslinger', 'VII', 'Vincent cannot be broken by opposing Summon or abilities that don\'t deal damage.</p><p></p><p>Death Penalty <img class="small-icon" src="/img/icons/special.png" />[5]<img class="small-icon" src="/img/icons/dull.png" />: Choose as many Forwards as you want with a total cost of 7 or less. Break them.', '77', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Vincent', '4', 'earth', 'forward', 'Gunslinger', 'VII', 'When Vincent attacks or blocks, you may pay 2. If you don\'t pay 2, Vincent breaks after the attack or the block and doesn\'t deal any damage.</p><p></p><p>When Vincent attacks or blocks, choose 1 Forward. Deal it 4000 damage.', '78', 'R', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ormi', '2', 'earth', 'forward', 'Sphere Hunter', 'X', 'The [Card Name (Logos)] and [Card Name [Leblanc)] you control gain +2000 power.', '79', 'R', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Carbuncle', '3', 'earth', 'summon', '', 'FFT', 'Choose 1 Summon targeting a Character you control. Cancel its effect.', '80', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Gabranth', '7', 'earth', 'forward', 'Judge', 'XII', 'The cost required to play Gabranth onto the field is reduced by 1 for each point of damage you have received.</p><p></p><p>If you have received 6 points of damage or more, the Earth Forwards you control gain <b>Brave</b>.', '81', 'L', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ranger', '2', 'earth', 'backup', 'Standard Unit', 'III', '<img class="small-icon" src="/img/icons/earth.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 attacking Earth Forward. It gains +1000 power until the end of the turn.', '82', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Machinist', '2', 'earth', 'backup', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/earth.png" /><img class="small-icon" src="/img/icons/earth.png" /><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">2</span></span><img class="small-icon" src="/img/icons/dull.png" />, put Machinist into the Break Zone: Choose 1 dull Forward of cost 4 or less. Break it.', '83', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Logos', '3', 'earth', 'forward', 'Sphere Hunter', 'X', 'The [Card Name (Ormi)] and [Card Name (Leblanc)] you control gain +2000 power.', '84', 'R', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Scarmiglione', '2', 'earth', 'forward', 'Archfiend', 'IV', 'Back Attack (Like Summon and abilities, this card can be played during either player\'s Attack Phase or Main Phase.)', '85', 'H', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Sorbet', '2', 'earth', 'backup', 'Moogle', 'XII', '<img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 blocking Forward. For each [Job (Moogle)] you control, it gains +1000 power until the end of the turn.', '86', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Hashmal, Bringer of Order', '1', 'earth', 'summon', '', 'XII', 'Name 1 Job or 1 Element. Until the end of the turn, all Forwards you control gain +1000 power and the named Job or Element.', '87', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ba\'Gamnan', '2', 'earth', 'forward', 'Headhunter', 'XII', 'Ba\'Gamnan cannot deal damage to your opponent. Opponent must block Ba\'Gamnan if possible.', '88', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Monk', '2', 'earth', 'backup', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/dull.png" />, put Monk into the Break Zone: Choose 1 Forward. It gains +3000 power and <b>Brave</b> until the end of the turn.', '89', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Yang', '5', 'earth', 'forward', 'Monk', 'IV', 'For each [Card Name (Monk)] and [Job (Monk)] other than Yang you control, Yang gains +1000 power.</p><p></p><p>If the power of Yang is 10000 or more, Yang gains <b>Brave</b>.', '90', 'R', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Yang', '2', 'earth', 'forward', 'Monk', 'IV', 'If you control a [Card Name (Monk)] or a [Job (Monk)] other than Yang, then Yang gains +2000 power and <b>Brave</b>.', '91', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Phantasmal Harlequin', '2', 'earth', 'backup', 'Mankin', 'DFF', '<img class="small-icon" src="/img/icons/dull.png" />: Choose 1 [Job (Manikin)] you control. It gains +2000 power until the end of the turn. When it is put from the field into the Break Zone this turn, break all the [Card Name (Phantasmal Harlequin)] you control.', '92', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Raubahn', '4', 'earth', 'backup', 'Flame General', 'XIV', 'EX BURST When Raubahn enters the field, choose 1 Forward you control and 1 Forward opponent controls. The first one deals damage to the second equal to its power.', '93', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rydia', '3', 'earth', 'forward', 'Summoner', 'IV', 'You may use Rydia\'s special ability by discarding an Earth Summon instead of discarding a [Card Name (Rydia)] as part of the cost.</p><p></p><p>Gaia\'s Wrath <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/wind.png" /><img class="small-icon" src="/img/icons/dull.png" /> : Deal 7000 damage to Forwards of all Elements except Earth.', '94', 'H', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rydia', '4', 'earth', 'backup', 'Summoner', 'IV', 'EX BURST When Tydia enters the field, choose 1 Earth Summon from your Break Zone. Add it to your hand.', '95', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Leblanc', '4', 'earth', 'forward', 'Sphere Hunter', 'X', '<b>Brave</b></p><p></p><p><img class="small-icon" src="/img/icons/dull.png" />, put 1 [Card Name (Ormi)] or 1 [Card Name (Logos)] into the Break Zone: Leblanc cannot be broken this turn.', '96', 'H', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Al-Cid', '4', 'lightning', 'forward', 'Agent', 'XII', 'When Al-Cid enters the field, choose 1 active Forward opponent controls. You may play 1 Lightning Forward of cost 3 or less from your hand onto the field. If you do so, deal it 6000 damage.', '97', 'H', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Amon', '4', 'lightning', 'forward', 'Technologist', 'XIV', 'When Amon enters the field, choose 1 Forward opponent controls. Dull it.</p><p></p><p><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Dull it.', '98', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Edea', '6', 'lightning', 'forward', 'Witch', 'VIII', 'EX BURST When Edea enters the field, choose 1 Forward opponent controls with a cost inferior or equal to the number of Lightning Backups you control. Break it.</p><p></p><p>Death <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" />: Choose 1 Forward. Break it.', '99', 'L', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Edea', '4', 'lightning', 'backup', 'Witch', 'VIII', 'Forwards of cost 5 or more cannot block.', '100', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Exdeath', '6', 'lightning', 'forward', 'Wizard', 'DFF - V', 'When Exdeath enters the field, you may play 1 [Job (Manikin)] of cost 4 or less from your hand onto the field.</p><p></p><p>The [Job (Manikin)] Forwards you control gain +1000 power.</p><p></p><p>For each [Job (Manikin)] you control, Exdeath gains +1000 power.', '101', 'H', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Gurdy', '2', 'lightning', 'backup', 'Moogle', 'XII', '<img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 active Forward opponent controls. Until the end of the turn, it loses 1000 power for each [Job (Moogle)] you control.', '102', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Kain', '3', 'lightning', 'forward', 'Dragoon', 'DFF - IV', '<b>Haste</b></p><p></p><p><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">1</span></span><img class="small-icon" src="/img/icons/dull.png" />: Kain cannot be chosen by your opponent\'s Summons or abilities until the beginning of your next turn. At the beginning of your next Main Phase and until the end of the same turn, Kain\'s power will double. You can only use this ability during your turn.', '103', 'H', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Kain', '4', 'lightning', 'forward', 'Dragoon', 'IV', 'If you control [Card Name (Rosa)], Kain gains +2000 power, <b>Haste</b> and <b>First Strike</b>.</p><p></p><p>The [Job (Dragoon)] and [Card Name (Dragoon)] Forwards other then Kain you </p><p>control gain +2000 power.', '104', 'R', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Kiros', '3', 'lightning', 'forward', 'Warrior', 'VIII', 'If you control [Card Name (Laguna)], Kiros gains +2000 power and <b>Haste</b>.', '105', 'C', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Gramis', '3', 'lightning', 'backup', 'Emperor', 'XII', 'When Gramis enters the field, you may search for 1 [Category (XII)] Forward and add it to your hand.', '106', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Cyclops', '3', 'lightning', 'summon', '', 'FFT', 'All Forwards opponent controls lose 3000 power until the end of the turn.', '107', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Black Mage', '2', 'lightning', 'backup', 'Standard Unit', 'XIV', 'When Black Mage enters the field, choose 1 Forward opponent controls. It loses 4000 power until the end of the turn.', '108', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Golbez', '8', 'lightning', 'forward', 'Warlock', 'IV', 'The cost to play Golbez onto the field is reduced by 2 for each [Job (Archfiend)] of different name put into your Break Zone.</p><p>When Golbez attacks, select 1 from the following. "Choose 1 Forward. Dull it." "Deal all Forwards opponent controls 3000 damage." "Choose 1 [Job (Archfiend)] from your Break Zone. Add it to your hand."', '109', 'H', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Seifer', '3', 'lightning', 'forward', 'SeeD Candidate', 'VIII', 'If you control [Card Name (Edea)], Seifer gains +3000 power and <b>Haste</b>.</p><p></p><p>No Mercy <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" /> : Break all the Forwards of cost 2 or less.', '110', 'R', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Seifer', '3', 'lightning', 'forward', 'SeeD Candidate', 'VIII', 'When Seifer blocks or is blocked, choose up to 2 Forwards. Deal them 3000 damage.', '111', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Fleeting Flash', '4', 'lightning', 'forward', 'Manikin', 'DFF', '</p><p><b>Haste</b></p><p></p><p>If you control a [Job (Manikin)] other then Fleeting Flash, Fleeting Flash gains +2000 power.', '112', 'C', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Drace', '3', 'lightning', 'forward', 'Judge', 'XII', 'If you control [Card Name (Larsa)], the cost to play Drace onto the field is reduced by 2 (it cannot become 0).</p><p></p><p>If you control [Card Name (Larsa)], Drace gains +2000 power and <b>First Strike</b>.', '113', 'R', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ninja', '2', 'lightning', 'forward', 'Standard Unit', 'FFT', '<img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" />: Break Ninja as well as the Forward that blocks or is blocked by Ninja.', '114', 'C', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ninja', '2', 'lightning', 'backup', 'Standard Unit', 'FFT', '<img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/lightning.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Deal it 2000 damage.', '115', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Fusoya', '3', 'lightning', 'backup', 'Lunarian', '4', 'When Fusoya enters the field, choose 1 Forward opponent controls. Deal it 5000 damage.</p><p></p><p>When Fusoya is put from the field into the Break Zone, choose 1 Forward from your Break Zone. Add it to your hand.', '116', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Adrammelech, the Wroth', '3', 'lightning', 'summon', '', 'XII', 'EX BURST Choose 1 active Forward. Deal it 7000 damage.', '117', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Arborous Simulacrum', '3', 'lightning', 'forward', 'Manikin', 'DFF', 'Any card of cost 2 or less put in the Damage Zone due to Arborous Simulacrum cannot use its EX Burst.', '118', 'C', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Reeve', '2', 'lightning', 'backup', 'Commissioner', 'VII', 'Reeve cannot be chosen by your opponent\'s Summons or abilities.</p><p></p><p>Inspire <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/dull.png" />: <b>Search</b> for 1 [Card Name (Caith Sith)] and add it to your hand.', '119', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Dragoon', '2', 'lightning', 'forward', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/lightning.png" />: : Dragoon gains <b>First Strike</b> until the end of the turn.', '120', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ashe', '3', 'water', 'forward', 'Princess', 'XII', 'When Ashe is chosen by a Summon or an ability of your opponent, Ashe gains +3000 power until the end of the turn.</p><p></p><p><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/water.png" />: Activate Ashe.</p><p></p><p><img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/water.png" />: Heaven\'s Wrath : Ashe gains +2000 power and <b>First Strike</b> until the end of the turn.', '121', 'H', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Agrias', '2', 'water', 'forward', 'Knight', 'FFT', 'Judgment Blade <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward of cost 3 or less opponent controls. Break it.', '122', 'R', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ephemeral Vision', '2', 'water', 'forward', 'Manikin', 'DFF', 'If you control 4 Forwards or more, Ephemeral Vision gains +3000 power.', '123', 'C', '4000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Cagnazzo', '2', 'water', 'forward', 'Archfiend', 'IV', 'Cagnazzo cannot block Forwards forming a party. When Cagnazzo blocks, dull Cagnazzo.</p><p></p><p>If Cagnazzo is dull, he cannot receive or deal any damage (this includes player damage too).', '124', 'H', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Semblance of a Witch', '3', 'water', 'forward', 'Manikin', 'DFF', 'When Semblance of a Witch enters the field, choose 1 Forward opponent controls. <b>Freeze</b> it.', '125', 'C', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Ghis', '5', 'water', 'forward', 'Judge', 'XII', 'When Ghis enters the field, you may play a Forward of any Element except Water and of cost 3 or less from your hand onto the field. If you do so, draw 2 cards, then discard 2 cards from your hand.</p><p>Ghis doesn\'t receive any damage from abilities other than special abilities.', '126', 'R', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Quistis', '5', 'water', 'forward', 'Instructor', 'VIII', 'When Quistis enters the field, you may play 1 Water Forward of cost 3 or less from your hand onto the field. The Forwards of cost 2 or less you control gain +1000 power.', '127', 'R', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Summoner', '3', 'water', 'backup', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/dull.png" />: Cast 1 Summon or cost 2 or less from your hand without paying the cost.', '128', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Cecil', '5', 'water', 'forward', 'Paladin', 'DFF - IV', 'If possible, Cecil must block.</p><p></p><p>Cecil doesn\'t receive any damage from Summons or abilities.</p><p></p><p>All Forwards other than Cecil you control gain +1000 power and don\'t receive any damage from Summons or abilities.', '129', 'L', '9000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Astrologian', '2', 'water', 'backup', 'Standard Unit', 'XIV', '<img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Active it.', '130', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Knight', '3', 'water', 'forward', 'Standard Unit', 'XIV', '', '131', 'C', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Viking', '1', 'water', 'forward', 'Standard Unit', 'III', 'When Viking leaves the field, draw 1 card.', '132', 'C', '1000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Cuchulainn, the Impure', '4', 'water', 'summon', '', 'XII', 'EX BURST Choose 1 Forward opponent controls. It loses 1000 power for each dull Character opponent controls until the end of the turn. Draw 1 card.', '133', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Horne', '2', 'water', 'backup', 'Moogle', 'XII', '<img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/dull.png" />: Draw 1 card for each [Job (Moogle)] you control. Then, place as many cards as drawn from your hand at the bottom of your deck in any order.', '134', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Porom', '3', 'water', 'forward', 'White Mage', 'IV', 'When Porom enters your field other than from your hand, choose 1 Forward of cost 5 or less. You may return it to its owner\'s hand.</p><p></p><p>Pyroblast <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/dull.png" />, dull 1 active [Card Name (Palom)]: Choose 1 Forward. Deal it 8000 damage.', '135', 'H', '6000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Porom', '1', 'water', 'forward', 'Apprentice Mage', 'IV', 'When Porom or the [Card Name (Palom)] you control is chosen by a Summon or an ability of your opponent, you may return it to its owner\'s hand.</p><p><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/dull.png" />, put Porom into the Break Zone: <b>Search</b> for 1 [Card Name (Porom)] and play it onto the field.', '136', 'R', '1000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Merlwyb', '4', 'water', 'backup', 'Admiral', 'XIV', 'EX BURST When Merlwyb enters the field, draw 2 cards then discard 1 card from your hand.', '137', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Yuna', '3', 'water', 'forward', 'Songstress', 'X', 'When Yuna attacks, all Characters other then Light and Dark opponent controls lose all their abilities until the end of the turn.</p><p></p><p>Spherechange <img class="small-icon" src="/img/icons/special.png" /> : Name 1 Element and 1 Job. Yuna becomes the named Element </p><p>and Job until the end of the turn.', '138', 'L', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Larsa', '2', 'water', 'forward', 'Fourthborn Son of the Emperor', 'XII', 'The Forwards you control don\'t receive damage that is less then their power.</p><p></p><p><img class="small-icon" src="/img/icons/water.png" /><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 blocking Forward. It gains +2000 power until the end of the turn.', '139', 'C', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Leviathan', '1', 'water', 'summon', '', 'VIII', 'EX BURST All Water Forwards gain +2000 power until the end of the turn.', '140', 'C', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Refia', '2', 'water', 'forward', 'Warrior of Light', 'III', 'The cost required to play your [Job (Standard Unit)] Forwards onto the field is reduced by 1 (it cannot become 0).', '141', 'H', '5000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Lenne', '3', 'water', 'forward', 'Songtress', 'X', 'When Lenne forms a party with [Card Name (Yuna)] and attacks, you may search for 1 Summon and cast it without paying the cost. If you do not cast it, put the Summon into the Break Zone. If you cast a Summon of cost 5 or more with this ability, put Lenne into the Break Zone.', '142', 'R', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rosa', '3', 'water', 'backup', 'White Mage', 'IV', 'Whenever a Forward you control is chosen by your opponent\'s Summon, you may draw 1 card.</p><p></p><p>Protect <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/dull.png" />: All the Forwards you control don\'t receive damage that is less than their power this turn.', '143', 'R', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Rosa', '1', 'water', 'forward', 'White Mage', 'IV', 'The [Card Name (Cecil)] you control gains +1000 power.</p><p></p><p><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Reduce the next damage dealt to it this turn by 1000.', '144', 'C', '3000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Warrior of Light', '0', 'light', 'forward', 'Warrior of Light', 'IV', 'Reduce the damage dealt to the [Job (Warrior of Light)] you control by 2000.</p><p></p><p>Bitter End <img class="small-icon" src="/img/icons/special.png" /><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">1</span></span><img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Deal it damage equal to Warrior of Light\'s power.', '145', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Fusoya', '3', 'light', 'backup', 'Lunarian', 'IV', '<img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. Deal it 7000 damage. Fusoya deals you 1 point of damage.', '146', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'The Emperor', '4', 'dark', 'forward', 'Emperor', 'II', 'The Characters opponent controls cannot use special or action abilities.', '147', 'L', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('2', 'Zemus', '4', 'dark', 'backup', 'Lunarian', 'IV', '<img class="small-icon" src="/img/icons/dull.png" />: Choose 1 Forward. It cannot be blocked this turn.', '148', 'H', '', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('pr', 'Sephiroth', '4', 'dark', 'forward', 'War Hero', 'VII', 'Hell\'s Gate <img class="small-icon" src="/img/icons/special.png" /><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">2</span></span>: Choose 1 Backup. Break it.', '1', '', '8000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('pr', 'Vincent', '3', 'earth', 'forward', 'Gunslinger', 'VII', 'Limit Break <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/earth.png" /><span class="fa-stack fa-1x"><i class="fa fa-circle-thin fa-stack-1x"></i><span class="fa-stack-1x">1</span></span>: Until the end of turn, Vincent gains +5000 power, <b>First Strike</b> and <b>Brave</b>.', '2', '', '7000', NOW());
INSERT IGNORE INTO cards (set_number, name, cost, element, type, job, category, text, card_number, rarity, power, created_at) VALUES ('pr', 'Lightning', '5', 'lightning', 'forward', 'Knight', 'XIII', 'Legion of One <img class="small-icon" src="/img/icons/special.png" /><img class="small-icon" src="/img/icons/lightning.png" />: Activate Lightning. Lightning gains <b>First Strike</b> until the end of the turn.', '3', '', '9000', NOW());
